export const GET_LOCAL_TASKS = 'GET_LOCAL_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const VIEW_TASK = 'VIEW_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const SELECT_TASK = 'SELECT_TASK';
export const REMOVE_MULTIPLE_TASK = 'REMOVE_MULTIPLE_TASK';
export const DONE_MULTIPLE_TASK = 'DONE_MULTIPLE_TASK'; 